import { supabase } from "@/integrations/supabase/client";
import { type StoreConfig } from "@/lib/store-config";
import { slugify } from "@/lib/slugify";

// Product source values. Extend the CHECK constraint in a new migration
// if you add new values here (e.g. 'import', 'api').
export type ProductSource = "ai" | "manual" | "import" | "api";

function isUUID(str: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(str);
}

export async function syncStoreCatalog(storeId: string, config: StoreConfig) {
  // 1. Fetch current categories in the database
  const { data: dbCategories, error: catError } = await supabase
    .from("categories")
    .select("id, name, slug, position")
    .eq("store_id", storeId);
  if (catError) throw new Error(`Failed to load categories: ${catError.message}`);

  const activeCategories = config.productCategories;
  const categoryNameToId: Record<string, string> = {};

  // 2. Synchronize categories
  for (let i = 0; i < activeCategories.length; i++) {
    const catName = activeCategories[i];
    const existing = dbCategories?.find((c) => c.name.toLowerCase() === catName.toLowerCase());

    if (existing) {
      if (existing.position !== i || existing.name !== catName) {
        const { error: updErr } = await supabase
          .from("categories")
          .update({ name: catName, position: i })
          .eq("id", existing.id);
        if (updErr) throw new Error(`Failed to update category: ${updErr.message}`);
      }
      categoryNameToId[catName] = existing.id;
    } else {
      const slug = slugify(catName) || `category-${i}`;
      const { data: newCat, error: insErr } = await supabase
        .from("categories")
        .insert({
          store_id: storeId,
          name: catName,
          slug,
          position: i,
        })
        .select("id")
        .single();
      if (insErr) throw new Error(`Failed to create category: ${insErr.message}`);
      categoryNameToId[catName] = newCat.id;
    }
  }

  // Delete categories no longer in the active list
  const activeIds = Object.values(categoryNameToId);
  const toDeleteCats = dbCategories?.filter((c) => !activeIds.includes(c.id)) ?? [];
  if (toDeleteCats.length > 0) {
    const { error: delErr } = await supabase
      .from("categories")
      .delete()
      .in(
        "id",
        toDeleteCats.map((c) => c.id),
      );
    if (delErr) throw new Error(`Failed to delete categories: ${delErr.message}`);
  }

  // 3. Fetch ONLY AI-owned products from the database.
  //
  // Scoping the query to source = 'ai' is the key safety boundary:
  // manual, import, and api products are invisible to the generator and
  // will never be modified or archived by this function, regardless of
  // their status.
  const { data: dbProducts, error: prodError } = await supabase
    .from("products")
    .select("id, name, status, sku")
    .eq("store_id", storeId)
    .eq("source" as any, "ai");
  if (prodError) throw new Error(`Failed to load products: ${prodError.message}`);

  const activeProducts = config.products;
  const activeProductIds: string[] = [];

  // -------------------------------------------------------------------------
  // OWNERSHIP MODEL — read carefully before modifying this block.
  //
  // source = 'ai'     → product was generated by the AI Generator
  // source = 'manual' → product was created by the store owner (dashboard)
  //
  // The generator owns the STRUCTURE of AI products (position, category,
  // lifecycle/status). The store owner owns the CONTENT of all products
  // (name, price, description, image) once they have been edited via the
  // dashboard.
  //
  // Rule for INSERT (new products):
  //   Write all fields. AI values are the starting point.
  //
  // Rule for UPDATE (existing AI products):
  //   Write structural fields only: category_id, position, status.
  //   Do NOT overwrite: name, base_price, description, image_url, currency.
  //   Reason: the store owner may have edited these fields from the dashboard
  //   after the product was first generated.
  //
  // Rule for MANUAL products:
  //   They are invisible to this function. The query in step 3 is scoped
  //   to source = 'ai', so manual/import/api products never appear here.
  //
  // TODO (Future — Phase 6+): If AI regeneration needs to overwrite owner-
  // edited content, implement a separate "content ownership" mechanism such as:
  //   - A content_owner field ('ai' | 'user') per product
  //   - A content_locked boolean
  //   - An explicit "Re-apply AI values" action in the Generator UI that
  //     presents a confirmation dialog before overwriting content fields.
  // -------------------------------------------------------------------------

  const productIdsMap: { originalId: string; dbId: string }[] = [];

  // 4. Synchronize AI-owned products
  for (let i = 0; i < activeProducts.length; i++) {
    const p = activeProducts[i];

    let prodId = p.id;
    let isNew = false;
    if (!isUUID(prodId)) {
      // Non-UUID id means the product came from mock/AI config data.
      // Try to match by name within the AI product scope.
      const existingDbProd = dbProducts?.find(
        (dp) => dp.name.toLowerCase() === p.name.toLowerCase(),
      );
      if (existingDbProd) {
        prodId = existingDbProd.id;
      } else {
        prodId = crypto.randomUUID();
        isNew = true;
      }
    } else {
      const exists = dbProducts?.some((dp) => dp.id === prodId);
      if (!exists) {
        isNew = true;
      }
    }

    productIdsMap.push({ originalId: p.id, dbId: prodId });

    const catId = p.category ? (categoryNameToId[p.category] ?? null) : null;
    const slug = slugify(p.name) || `product-${i}`;

    if (isNew) {
      // Full insert — AI values are the initial content for a brand new product.
      const insertPayload = {
        id: prodId,
        store_id: storeId,
        source: "ai",
        category_id: catId,
        name: p.name,
        slug,
        base_price: p.price,
        currency: config.currency,
        status: "active" as const,
        image_url: p.image || null,
        description: p.description ?? null,
        position: i,
      };
      const { error: insErr } = await supabase.from("products").insert(insertPayload as any);
      if (insErr) throw new Error(`Failed to insert product ${p.name}: ${insErr.message}`);
    } else {
      // Structural update only — do NOT touch owner-editable content fields.
      // name, base_price, description, image_url, currency are intentionally
      // excluded to preserve any dashboard edits the owner may have made.
      const structuralPatch = {
        category_id: catId,
        position: i,
        status: "active" as const,
      };
      const { error: updErr } = await supabase
        .from("products")
        .update(structuralPatch)
        .eq("id", prodId);
      if (updErr) throw new Error(`Failed to update product ${p.name}: ${updErr.message}`);
    }

    activeProductIds.push(prodId);
  }

  // 5. Soft-archive AI products that are no longer in the generator config.
  //
  // Safety guarantees enforced by the query in step 3 above:
  //   - dbProducts contains ONLY source='ai' rows, so manual/import/api
  //     products can never appear in toSoftDelete.
  //   - We additionally guard against re-archiving already-archived AI
  //     products by checking status === 'active'.
  const toSoftDelete =
    dbProducts?.filter((dp) => dp.status === "active" && !activeProductIds.includes(dp.id)) ?? [];

  if (toSoftDelete.length > 0) {
    const { error: softDelErr } = await supabase
      .from("products")
      .update({ status: "archived" })
      .in(
        "id",
        toSoftDelete.map((dp) => dp.id),
      );
    if (softDelErr) throw new Error(`Failed to soft-archive products: ${softDelErr.message}`);
  }

  // 6. Update store catalog_source = 'relational'
  const { error: storeUpdErr } = await supabase
    .from("stores")
    .update({ catalog_source: "relational" })
    .eq("id", storeId);
  if (storeUpdErr) throw new Error(`Failed to update store catalog source: ${storeUpdErr.message}`);

  return { products: productIdsMap };
}
