/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedGeneratorRouteImport } from './routes/_authenticated/generator'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStoresStoreIdRouteImport } from './routes/_authenticated/stores.$storeId'
import { Route as AuthenticatedStoresStoreIdCategoriesRouteImport } from './routes/_authenticated/stores.$storeId.categories'
import { Route as AuthenticatedStoresStoreIdProductsIndexRouteImport } from './routes/_authenticated/stores.$storeId.products.index'
import { Route as AuthenticatedStoresStoreIdProductsNewRouteImport } from './routes/_authenticated/stores.$storeId.products.new'
import { Route as AuthenticatedStoresStoreIdProductsProductIdRouteImport } from './routes/_authenticated/stores.$storeId.products.$productId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeneratorRoute = AuthenticatedGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoresStoreIdRoute =
  AuthenticatedStoresStoreIdRouteImport.update({
    id: '/stores/$storeId',
    path: '/stores/$storeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreIdCategoriesRoute =
  AuthenticatedStoresStoreIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)
const AuthenticatedStoresStoreIdProductsIndexRoute =
  AuthenticatedStoresStoreIdProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)
const AuthenticatedStoresStoreIdProductsNewRoute =
  AuthenticatedStoresStoreIdProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)
const AuthenticatedStoresStoreIdProductsProductIdRoute =
  AuthenticatedStoresStoreIdProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedStoresStoreIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/s/$slug': typeof SSlugRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRouteWithChildren
  '/stores/$storeId/categories': typeof AuthenticatedStoresStoreIdCategoriesRoute
  '/stores/$storeId/products/$productId': typeof AuthenticatedStoresStoreIdProductsProductIdRoute
  '/stores/$storeId/products/new': typeof AuthenticatedStoresStoreIdProductsNewRoute
  '/stores/$storeId/products/': typeof AuthenticatedStoresStoreIdProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generator': typeof AuthenticatedGeneratorRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/s/$slug': typeof SSlugRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRouteWithChildren
  '/stores/$storeId/categories': typeof AuthenticatedStoresStoreIdCategoriesRoute
  '/stores/$storeId/products/$productId': typeof AuthenticatedStoresStoreIdProductsProductIdRoute
  '/stores/$storeId/products/new': typeof AuthenticatedStoresStoreIdProductsNewRoute
  '/stores/$storeId/products': typeof AuthenticatedStoresStoreIdProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/generator': typeof AuthenticatedGeneratorRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/stores/$storeId': typeof AuthenticatedStoresStoreIdRouteWithChildren
  '/_authenticated/stores/$storeId/categories': typeof AuthenticatedStoresStoreIdCategoriesRoute
  '/_authenticated/stores/$storeId/products/$productId': typeof AuthenticatedStoresStoreIdProductsProductIdRoute
  '/_authenticated/stores/$storeId/products/new': typeof AuthenticatedStoresStoreIdProductsNewRoute
  '/_authenticated/stores/$storeId/products/': typeof AuthenticatedStoresStoreIdProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/generator'
    | '/settings'
    | '/templates'
    | '/s/$slug'
    | '/stores/$storeId'
    | '/stores/$storeId/categories'
    | '/stores/$storeId/products/$productId'
    | '/stores/$storeId/products/new'
    | '/stores/$storeId/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/generator'
    | '/settings'
    | '/templates'
    | '/s/$slug'
    | '/stores/$storeId'
    | '/stores/$storeId/categories'
    | '/stores/$storeId/products/$productId'
    | '/stores/$storeId/products/new'
    | '/stores/$storeId/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/generator'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/s/$slug'
    | '/_authenticated/stores/$storeId'
    | '/_authenticated/stores/$storeId/categories'
    | '/_authenticated/stores/$storeId/products/$productId'
    | '/_authenticated/stores/$storeId/products/new'
    | '/_authenticated/stores/$storeId/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SSlugRoute: typeof SSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generator': {
      id: '/_authenticated/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AuthenticatedGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeId': {
      id: '/_authenticated/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeId/categories': {
      id: '/_authenticated/stores/$storeId/categories'
      path: '/categories'
      fullPath: '/stores/$storeId/categories'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdCategoriesRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
    '/_authenticated/stores/$storeId/products/': {
      id: '/_authenticated/stores/$storeId/products/'
      path: '/products'
      fullPath: '/stores/$storeId/products/'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdProductsIndexRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
    '/_authenticated/stores/$storeId/products/new': {
      id: '/_authenticated/stores/$storeId/products/new'
      path: '/products/new'
      fullPath: '/stores/$storeId/products/new'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdProductsNewRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
    '/_authenticated/stores/$storeId/products/$productId': {
      id: '/_authenticated/stores/$storeId/products/$productId'
      path: '/products/$productId'
      fullPath: '/stores/$storeId/products/$productId'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedStoresStoreIdRoute
    }
  }
}

interface AuthenticatedStoresStoreIdRouteChildren {
  AuthenticatedStoresStoreIdCategoriesRoute: typeof AuthenticatedStoresStoreIdCategoriesRoute
  AuthenticatedStoresStoreIdProductsProductIdRoute: typeof AuthenticatedStoresStoreIdProductsProductIdRoute
  AuthenticatedStoresStoreIdProductsNewRoute: typeof AuthenticatedStoresStoreIdProductsNewRoute
  AuthenticatedStoresStoreIdProductsIndexRoute: typeof AuthenticatedStoresStoreIdProductsIndexRoute
}

const AuthenticatedStoresStoreIdRouteChildren: AuthenticatedStoresStoreIdRouteChildren =
  {
    AuthenticatedStoresStoreIdCategoriesRoute:
      AuthenticatedStoresStoreIdCategoriesRoute,
    AuthenticatedStoresStoreIdProductsProductIdRoute:
      AuthenticatedStoresStoreIdProductsProductIdRoute,
    AuthenticatedStoresStoreIdProductsNewRoute:
      AuthenticatedStoresStoreIdProductsNewRoute,
    AuthenticatedStoresStoreIdProductsIndexRoute:
      AuthenticatedStoresStoreIdProductsIndexRoute,
  }

const AuthenticatedStoresStoreIdRouteWithChildren =
  AuthenticatedStoresStoreIdRoute._addFileChildren(
    AuthenticatedStoresStoreIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGeneratorRoute: typeof AuthenticatedGeneratorRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedStoresStoreIdRoute: typeof AuthenticatedStoresStoreIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGeneratorRoute: AuthenticatedGeneratorRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedStoresStoreIdRoute: AuthenticatedStoresStoreIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SSlugRoute: SSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
